recipe: default.v1
language: el
pipeline:

- name: NLUCommandAdapter
- name: LLMCommandGenerator
  llm:
    model_name: "gpt-4"
    
policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  llm:
      model_name: "gpt-3.5-turbo"
  vector_store:
      type: "faiss"
      source: "./docs"

assistant_id: 20240628-201941-basic-vector
